spring.application.name=api_envoice

# POSTGRES
spring.datasource.url=jdbc:postgresql://localhost:5432/envoice_dev_db
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=postgres
spring.datasource.password=123456

# FLYWAY
spring.flyway.enabled=true
#spring.flyway.locations=classpath:db/migration
spring.flyway.locations=classpath:db/migration,classpath:db/migration/dev

# REPORT
empresa.nombre=Mi Empresa SAC
empresa.ruc=20123456789
empresa.direccion=Av. Siempre Viva 742
empresa.telefono=999999999

pago.banco=Banco Santander
pago.iban=ES12 xxxx xxxx xxxx
pago.bic=ABCxxx